<a href="https://colab.research.google.com/github/catherineHZN/DeepLearningTutorials/blob/main/TensorFlow/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# In this notebook we will cover tensorflow fundamentals


# In this notebook we will cover tensors with tensorflow fundamentals.

In [ ]:
## Introduction to Tensors
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of the dimensiton
scalar.ndim

0

In [ ]:
# create vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[1,13],[5,7]])

In [ ]:
matrix.ndim

2

In [ ]:
print(matrix)

tf.Tensor(
[[ 1 13]
 [ 5  7]], shape=(2, 2), dtype=int32)


In [ ]:
matrix2 = tf.constant([[1, 2],[3,5],[5,6]])

In [ ]:
matrix2.ndim

2

In [ ]:
print(matrix2)

tf.Tensor(
[[1 2]
 [3 5]
 [5 6]], shape=(3, 2), dtype=int32)


In [ ]:
## Basically: the ndim gives the dimenstion of a  tensor, while shape gives the number of rows colums.. of the tensor

In [ ]:
print(matrix2.ndim)
matrix2.shape

2


TensorShape([3, 2])

vector = tf.constant([([1, 2], [3,4]),([5,6], [6,7]),([8,9],[10,11])])

In [ ]:
vector = tf.constant([([1, 2], [3,4]),([5,6], [6,7]),([8,9],[10,11])])

In [ ]:
print(vector.ndim)
vector.shape

3


TensorShape([3, 2, 2])

In [ ]:
print(vector)

tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 6  7]]

 [[ 8  9]
  [10 11]]], shape=(3, 2, 2), dtype=int32)


In [ ]:
another_matrix = tf.constant([[1,2],[3,5],[7,13]], dtype=tf.float16)

In [ ]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 1.,  2.],
       [ 3.,  5.],
       [ 7., 13.]], dtype=float16)>

In [ ]:
changeable_tensor = tf.Variable([10,8,11])
changeable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10,  8, 11], dtype=int32)>

In [ ]:
changeable_tensor[0] = 23
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
changeable_tensor[0].assign(23)
changeable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([23,  8, 11], dtype=int32)>

In [ ]:
vector[0].assign(33)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
r_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
r_2 = random_2.normal(shape = (3,2))


r_1 , r_2 , r_1 == r_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
r_3 = random_1.normal(shape = (2,1))
r_3

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 1.4680984 ],
       [-0.69443417]], dtype=float32)>

In [ ]:
# Create two random (and different) tensors
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

# Check the tensors and see if they are equal
random_3, random_4, r_1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
not_shuffled = tf.constant([[1,2],[3,4],[5,6]])
not_shuffled
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed = 43)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

### Creating random tensors

In [ ]:
random_5 = tf.random.Generator.from_seed(51)
random_5 = random_5.normal(shape = (3,2))
random_6 = tf.random.Generator.from_seed(51)
random_6 = random_6.normal(shape = (3,2))
random_5, random_6, random_5 == random_6

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 2.006022  ,  0.28288034],
        [-0.30288252, -1.443651  ],
        [ 1.0034493 ,  0.20857747]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 2.006022  ,  0.28288034],
        [-0.30288252, -1.443651  ],
        [ 1.0034493 ,  0.20857747]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffiling data

In [ ]:
tf.random.set_seed(42)
not_shuffled = tf.constant([[17,7],[3,4],[2,5]])
not_shuffled.ndim
not_shuffled.shape

tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[17,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### otherways to make tensors

In [ ]:
#numpy like operatios
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([3,6])

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Creating tensors from numpy arrays


## Turn NumPy arrays to tensors

The main difference between NumPy arrays and TensorFlow tensors is tgat tensors can be run on a GPU(much faster for numerical computing)


In [ ]:
#Turning NumPy arrays to tensors
import numpy as np

numpy_A = np.arange(1,25,dtype= np.int32)
numpy_A
# X = tf.constant(some_matrix) #capitalize for matrix
# y = tf.constant(some_vector) # smal or vectors and scalars

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A.shape

TensorShape([24])

In [ ]:
B = tf.constant(numpy_A,shape = (2, 3,4) )
A,B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

### Get more information from our tensors

* shape : tensor.shape
* rank : tensoe.ndim
* size: tf.size(tensor)
* Axis or dimension: tensor[0] ...

In [ ]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
# create a rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim , tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


### Indexing tensors
Tensors can be indexed just like Python lists

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2 ,:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
some_list[:1]

[1]

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1 ,:1, :1, :]


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# create a ranks 2 tensor (2 dimensions)

rank_2_tensor = tf.constant([  [2,7] , [3,6] ])
rank_2_tensor.ndim

2

In [ ]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 6], dtype=int32)>

### Adding dimensions to a tensor while keeping the information present using tf.newaxis

In [ ]:
#Add an extra diminsion (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
# in python  ... means all dimensions prior to
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 7],
        [3, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[2],
         [7]],
 
        [[3],
         [6]]], dtype=int32)>)