<a href="https://colab.research.google.com/github/catherineHZN/DeepLearningTutorials/blob/main/TensorFlow/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# In this notebook we will cover tensorflow fundamentals


# In this notebook we will cover tensors with tensorflow fundamentals.

In [4]:
## Introduction to Tensors
import tensorflow as tf
print(tf.__version__)

2.17.1


In [5]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# check the number of the dimensiton
scalar.ndim

0

In [7]:
# create vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vector.ndim

1

In [9]:
matrix = tf.constant([[1,13],[5,7]])

In [10]:
matrix.ndim

2

In [11]:
print(matrix)

tf.Tensor(
[[ 1 13]
 [ 5  7]], shape=(2, 2), dtype=int32)


In [12]:
matrix2 = tf.constant([[1, 2],[3,5],[5,6]])

In [13]:
matrix2.ndim

2

In [14]:
print(matrix2)

tf.Tensor(
[[1 2]
 [3 5]
 [5 6]], shape=(3, 2), dtype=int32)


In [15]:
## Basically: the ndim gives the dimenstion of a  tensor, while shape gives the number of rows colums.. of the tensor

In [16]:
print(matrix2.ndim)
matrix2.shape

2


TensorShape([3, 2])

vector = tf.constant([([1, 2], [3,4]),([5,6], [6,7]),([8,9],[10,11])])

In [17]:
vector = tf.constant([([1, 2], [3,4]),([5,6], [6,7]),([8,9],[10,11])])

In [18]:
print(vector.ndim)
vector.shape

3


TensorShape([3, 2, 2])

In [19]:
print(vector)

tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 6  7]]

 [[ 8  9]
  [10 11]]], shape=(3, 2, 2), dtype=int32)


In [20]:
another_matrix = tf.constant([[1,2],[3,5],[7,13]], dtype=tf.float16)

In [21]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 1.,  2.],
       [ 3.,  5.],
       [ 7., 13.]], dtype=float16)>

In [22]:
changeable_tensor = tf.Variable([10,8,11])
changeable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10,  8, 11], dtype=int32)>

In [23]:
changeable_tensor[0] = 23
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [24]:
changeable_tensor[0].assign(23)
changeable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([23,  8, 11], dtype=int32)>

In [25]:
vector[0].assign(33)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [27]:
random_1 = tf.random.Generator.from_seed(42)
r_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
r_2 = random_2.normal(shape = (3,2))


r_1 , r_2 , r_1 == r_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [28]:
r_3 = random_1.normal(shape = (2,1))
r_3

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.17522676],
       [0.71105534]], dtype=float32)>

In [29]:
# Create two random (and different) tensors
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

# Check the tensors and see if they are equal
random_3, random_4, r_1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [30]:
not_shuffled = tf.constant([[1,2],[3,4],[5,6]])
not_shuffled
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]], dtype=int32)>

In [31]:
tf.random.shuffle(not_shuffled, seed = 43)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]], dtype=int32)>

### Creating random tensors

In [32]:
random_5 = tf.random.Generator.from_seed(51)
random_5 = random_5.normal(shape = (3,2))
random_6 = tf.random.Generator.from_seed(51)
random_6 = random_6.normal(shape = (3,2))
random_5, random_6, random_5 == random_6

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 2.006022  ,  0.28288034],
        [-0.30288252, -1.443651  ],
        [ 1.0034493 ,  0.20857747]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 2.006022  ,  0.28288034],
        [-0.30288252, -1.443651  ],
        [ 1.0034493 ,  0.20857747]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffiling data

In [33]:
tf.random.set_seed(42)
not_shuffled = tf.constant([[17,7],[3,4],[2,5]])
not_shuffled.ndim
not_shuffled.shape

tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[17,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### otherways to make tensors

In [34]:
#numpy like operatios
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [35]:
tf.zeros([3,6])

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Creating tensors from numpy arrays


## Turn NumPy arrays to tensors

The main difference between NumPy arrays and TensorFlow tensors is tgat tensors can be run on a GPU(much faster for numerical computing)


In [36]:
#Turning NumPy arrays to tensors
import numpy as np

numpy_A = np.arange(1,25,dtype= np.int32)
numpy_A
# X = tf.constant(some_matrix) #capitalize for matrix
# y = tf.constant(some_vector) # smal or vectors and scalars

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [37]:
A = tf.constant(numpy_A)
A.shape

TensorShape([24])

In [38]:
B = tf.constant(numpy_A,shape = (2, 3,4) )
A,B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

### Get more information from our tensors

* shape : tensor.shape
* rank : tensoe.ndim
* size: tf.size(tensor)
* Axis or dimension: tensor[0] ...

In [39]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [40]:
# create a rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [41]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [42]:
rank_4_tensor.shape, rank_4_tensor.ndim , tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [43]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


### Indexing tensors
Tensors can be indexed just like Python lists

In [44]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2 ,:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [45]:
some_list[:1]

[1]

In [46]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1 ,:1, :1, :]


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [47]:
# create a ranks 2 tensor (2 dimensions)

rank_2_tensor = tf.constant([  [2,7] , [3,6] ])
rank_2_tensor.ndim

2

In [48]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 6], dtype=int32)>

### Adding dimensions to a tensor while keeping the information present using tf.newaxis

In [49]:
#Add an extra diminsion (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
# in python  ... means all dimensions prior to
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 7],
        [3, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[2],
         [7]],
 
        [[3],
         [6]]], dtype=int32)>)

rank_3_newtensor =  tf.expand_dims(rank_2_tensor, axis = -1)
rank_3_newtensor, rank_2_tensor

### Manipulating  tensors (tensor operations)
**Basic operation**
'+', '-', '*', '\\'

In [50]:
# adding values to a tensor using the addition operator
tensor = tf.constant([[11,13], [29, 4]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 23],
       [39, 14]], dtype=int32)>

In [51]:
# the original tensor remains unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 13],
       [29,  4]], dtype=int32)>

In [52]:
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 23],
       [39, 14]], dtype=int32)>

In [53]:
# multiplications
tensor * 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[210, 230],
       [390, 140]], dtype=int32)>

In [54]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 13],
       [29,  4]], dtype=int32)>

In [55]:
# We can use the tensorflow biultin functions too
# Using these functions id better because their implementation is more efficient specially on GPUs.


tf.multiply(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 46],
       [78, 28]], dtype=int32)>

In [56]:
tf.add(tensor, 4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 27],
       [43, 18]], dtype=int32)>

### Matrix multiplications

In [57]:
# Matrix multiplation
matrix1 = tf.constant([[1, 2,3],[4,5,6],[7,8,9]])
matrix1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [58]:
matrix2 = tf.constant([[10, 11],[15, 16], [7, 10]])
matrix2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 11],
       [15, 16],
       [ 7, 10]], dtype=int32)>

In [59]:
tf.matmul(matrix1, matrix2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 61,  73],
       [157, 184],
       [253, 295]], dtype=int32)>

In [60]:
# elementwise muliplication
matrix1 * matrix1
tf.multiply(matrix1, matrix1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)>

In [61]:
# Matrix muliplication using python operator "@"
# regular "algebra" matrix muliplication using python standard operator @
matrix1 @ matrix2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 61,  73],
       [157, 184],
       [253, 295]], dtype=int32)>

In [62]:
matrix1.shape

TensorShape([3, 3])

In [63]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[4,5],
 [7,8],
 [10,10]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 4,  5],
        [ 7,  8],
        [10, 10]], dtype=int32)>)

In [64]:
tf.multiply(X, Y) # this is elementwise multiplication

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4, 10],
       [21, 32],
       [50, 60]], dtype=int32)>

In [65]:
# changing the shape of Y
tf.reshape(Y, shape=(2,3)) , Y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 4,  5,  7],
        [ 8, 10, 10]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 4,  5],
        [ 7,  8],
        [10, 10]], dtype=int32)>)

In [66]:
tf.reshape(Y, shape=(2,3)) @ X

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 54,  70],
       [ 88, 116]], dtype=int32)>

In [67]:
# Transpose operation
tf.transpose(X) , X

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)



```
# This is formatted as code
```

 **The dot product**

 Matrix multiplication is also referred to as a dot product. You can perform matrix multiplication using:
 * `tf.matmul()`
 * `tf.tensordot()`


In [69]:
#perform the dot product on X and Y
X.shape, Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [71]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 75,  79],
       [ 96, 102]], dtype=int32)>

In [72]:
# perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 14,  23,  30],
       [ 32,  53,  70],
       [ 50,  83, 110]], dtype=int32)>

In [73]:
# perform matrix product between X and Y reshaped

tf.matmul(X, tf.reshape(Y, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[20, 25, 27],
       [44, 55, 61],
       [68, 85, 95]], dtype=int32)>

In [74]:
tf.reshape(Y, shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4,  5,  7],
       [ 8, 10, 10]], dtype=int32)>

In [76]:
Y, tf.transpose(Y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 4,  5],
        [ 7,  8],
        [10, 10]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 4,  7, 10],
        [ 5,  8, 10]], dtype=int32)>)

### Changing the datatype of a tensor

In [85]:
# Create a new tensor with the default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [86]:
C = tf.constant([11,14])
C.dtype

tf.int32

Apparently, the default type is inferred by the type of the numbers we pass to tf.constant()

In [87]:
BB = tf.constant([1.5, 7])
BB.dtype

tf.float32

In [89]:
# change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype = tf.float16 )
D.dtype,D,  B.dtype, B

(tf.float16,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float32,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>)

In [90]:
# change from int32 to flaot32
E = tf.cast(C, dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([11., 14.], dtype=float32)>

In [92]:
E_float16 = tf.cast(E, dtype = tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([11., 14.], dtype=float16)>

###Aggregating tensors
Aggregating tensors is condensing them from multiple values down to a smaller amount of values
* abs

In [93]:
# Getting the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [94]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go througth the following forms of aggregation:
* Get the abstact value using tf.abs()
* Get the minimum usfing `tf.reduce_min`
* Get the maximum using `tf.reduce_max()`
* Get the mean of a tensor using `tf.reduce_mean()`
* Get the sum of a tensor using `tf.reduce_sum()`


In [96]:
V = tf.constant([[1,2,3] , [4,5,6]
                 ])
V

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
# V is the followinf matrix:
# 1,2,3
# 4,5,6

In [97]:
# Taking the minimum over the rows of V
# This will result in a single number per row
# Therefore, in the case of V we will end up a tensor that include (#rows,) shape.
# When specifing axis = 1
tf.reduce_min(V, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

In [101]:
# Taking the minimum over the columns of V
# This will result in a single number per column
# Therefore, in the case of V we will end up a tensor that include (#colums,) shape.
# When specifing axis = 0
tf.reduce_min(V, axis = 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [99]:
# If no axis is specified, then the minimum is taken over all the numbers in the tensor
# resulting in a single number tensor (effectivally a scalar)
tf.reduce_min(V)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [102]:
# Same logic holds applying axis=? to the other reduce operation
#here is an example of reduce_mean
# take mean ove the rows
tf.reduce_mean(V, axis = 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>

In [103]:
tf.reduce_mean(V, axis = 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [104]:
tf.reduce_mean(V)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [124]:
E = tf.constant(np.random.randint(0,100, size = 5))
#E = tf.constant([2,4,4,4,5,5,7,9])
E

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([21,  1, 94, 63, 20])>

**Exercise:** Find the Standard variance and deviation of E

In [125]:
# Expectation
mu = tf.reduce_mean(E)
mu

<tf.Tensor: shape=(), dtype=int64, numpy=39>

In [126]:
variance = tf.reduce_mean((E-mu)*(E-mu))
variance

<tf.Tensor: shape=(), dtype=int64, numpy=1146>

In [127]:
deviation = tf.sqrt(tf.cast(variance, dtype = tf.float16))
deviation

<tf.Tensor: shape=(), dtype=float16, numpy=33.84>

In [128]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1146>

In [135]:
tfp.stats.stddev(tf.cast(E, dtype=tf.float32))


<tf.Tensor: shape=(), dtype=float32, numpy=33.84317>

In [136]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=1145.3601>

In [137]:
tf.math.reduce_std(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=33.84317>

###Find the positional maximum and minimum of a tensor

In [139]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [140]:
# Find the positional maximum - use tf.argmax
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [141]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [142]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [145]:
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [146]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [147]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [148]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [149]:
# Create a tensor to get started ...
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [152]:
G = tf.squeeze(G)
G, G.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One Hot encoding tensors

In [161]:
# Create a list of indexes
some_list = [0,1,2,3] # chould be categories for red, gree, blue and pruple

# One hot encoding of out list of indicies
tf.one_hot(some_list, depth = 4, on_value=3, off_value=9)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[3, 9, 9, 9],
       [9, 3, 9, 9],
       [9, 9, 3, 9],
       [9, 9, 9, 3]], dtype=int32)>

### Few common math operations: squaring, log, and square root

In [163]:
# Create a new tensor
H= tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [164]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [166]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [169]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Numpy and tensorflow compitability
TensorFlow interacts beatifully with NumPy

In [170]:
# Creat a tensor directrly from a numpy array

I = tf.constant(np.array([3., 6., 7.]))
I

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 6., 7.])>

In [172]:
# Converting a tensor to NumPy array
np.array(I), type(np.array(I))

(array([3., 6., 7.]), numpy.ndarray)

In [173]:
# Convert a tensor I to a NumPy array
I.numpy(), type(I.numpy())

(array([3., 6., 7.]), numpy.ndarray)

In [174]:
# Why this isusefyl - have a quick access
J = tf.constant([3.])
J.numpy()[0]

3.0

In [178]:
# The default type of each are slightly different
numpy_J = tf.constant(np.array([3., 4., 7.]))
tensor_J = tf.constant([3., 4., 7.])
numpy_J.dtype, tensor_J.dtype



(tf.float64, tf.float32)

### Finding access to GPUs

In [2]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Tue Nov 19 14:58:37 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8              10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

**Note**: if you have access to a CUDA-enables GPU, TensorFlow will automatically use it whenever possible

**Note** CUDA is an interface between TensorFlow and GPU that makes the GPU run really fast